package app.shackcq.mobile.hamclock

internal enum class HamClockModuleCategory { STATION, MAP, RF, SPACE_WEATHER, ACTIVITY, OPERATIONS }
internal enum class HamClockModuleAvailability { ACTIVE, DELEGATED, UNAVAILABLE }
internal enum class HamClockModuleRenderer {
    MAP, STATION, WEATHER, PSK_REPORTER, DX_NEWS, DX_EXPEDITIONS, BAND_ACTIVITY, DX_CLUSTER,
    SOLAR, DX_TARGET, PROPAGATION, PORTABLE, SATELLITES, CONTESTS, ANALOG_CLOCK,
    RBN, WSPR, IBP, BAND_HEALTH, NEURAL_OUTLOOK, LEGACY,
}
internal enum class HamClockDeepLink { NONE, DX, PORTABLE, OPERATIONS, LOGBOOK, LOG_INTELLIGENCE, RADIO, DIGI }

internal data class HamClockModuleSpec(
    val id: String,
    val upstreamIds: Set<String>,
    val title: String,
    val category: HamClockModuleCategory,
    val visualRole: String,
    val defaultVisible: Boolean,
    val defaultColumn: Int,
    val defaultOrder: Int,
    val defaultColumnSpan: Int = 1,
    val defaultRowSpan: Int = 1,
    val allowedColumns: Set<Int> = setOf(0, 2),
    val minimumWidthDp: Int = 220,
    val preferredHeightDp: Int = 220,
    val collapseSupported: Boolean = true,
    val availability: HamClockModuleAvailability = HamClockModuleAvailability.ACTIVE,
    val unavailableReason: String = "",
    val sourceLabel: String = "ShackCQ",
    val renderer: HamClockModuleRenderer,
    val deepLink: HamClockDeepLink = HamClockDeepLink.NONE,
    val lowDataRepresentation: String,
)

internal val hamClockModuleRegistry: List<HamClockModuleSpec> = listOf(
    HamClockModuleSpec(HamClockPanelId.STATION, setOf("de-location", "rig-control", "on-air"), "DE station",
        HamClockModuleCategory.STATION, "identity-radio-safety", true, 0, 0, preferredHeightDp = 390,
        sourceLabel = "Local station · live CAT", renderer = HamClockModuleRenderer.STATION,
        deepLink = HamClockDeepLink.RADIO, lowDataRepresentation = "Station, CAT and TX-safety rows"),
    HamClockModuleSpec(HamClockPanelId.WEATHER, setOf("ambient"), "Local weather",
        HamClockModuleCategory.STATION, "weather-summary", true, 0, 1,
        sourceLabel = "Open-Meteo", renderer = HamClockModuleRenderer.WEATHER,
        lowDataRepresentation = "Temperature, pressure and wind rows"),
    HamClockModuleSpec(HamClockPanelId.PSK_REPORTER, setOf("psk-reporter"), "PSK Reporter",
        HamClockModuleCategory.RF, "signal-reports", true, 0, 2, preferredHeightDp = 285,
        sourceLabel = "PSK Reporter", renderer = HamClockModuleRenderer.PSK_REPORTER,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Bounded reception-report rows"),
    HamClockModuleSpec(HamClockPanelId.DX_NEWS, setOf("dx-news-ticker", "dx-news-sources", "dx-news-merge"), "DX News",
        HamClockModuleCategory.ACTIVITY, "source-attributed-headlines", true, 0, 3, preferredHeightDp = 285,
        sourceLabel = "DX-World · NG3K", renderer = HamClockModuleRenderer.DX_NEWS,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Static current headline with source and age"),
    HamClockModuleSpec(HamClockPanelId.DX_EXPEDITIONS, setOf("dxpeditions"), "DXpeditions",
        HamClockModuleCategory.ACTIVITY, "schedule", true, 0, 4, preferredHeightDp = 210,
        sourceLabel = "NG3K ADXO", renderer = HamClockModuleRenderer.DX_EXPEDITIONS,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Current schedule rows"),
    HamClockModuleSpec(HamClockPanelId.MAP, setOf("world-map", "map-list-view"), "World activity",
        HamClockModuleCategory.MAP, "interactive-map", true, 1, 0, defaultColumnSpan = 2,
        allowedColumns = setOf(1), minimumWidthDp = 320, preferredHeightDp = 390,
        collapseSupported = false, sourceLabel = "ShackCQ map authorities",
        renderer = HamClockModuleRenderer.MAP, deepLink = HamClockDeepLink.DX,
        lowDataRepresentation = "Complete bounded Map Data view"),
    HamClockModuleSpec(HamClockPanelId.DX_CLUSTER, setOf("dx-cluster"), "DX cluster",
        HamClockModuleCategory.ACTIVITY, "live-spots", true, 2, 0, preferredHeightDp = 500,
        sourceLabel = "Configured DX cluster", renderer = HamClockModuleRenderer.DX_CLUSTER,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Filtered spot rows"),
    HamClockModuleSpec(HamClockPanelId.SOLAR, setOf("solar", "solar-indices", "solar-xray", "lunar"),
        "Solar conditions", HamClockModuleCategory.SPACE_WEATHER, "solar-and-celestial", true, 2, 1,
        preferredHeightDp = 240, sourceLabel = "NOAA SWPC · local astronomy",
        renderer = HamClockModuleRenderer.SOLAR, lowDataRepresentation = "Indices, X-ray and celestial rows"),
    HamClockModuleSpec(HamClockPanelId.DX_TARGET, setOf("dx-location"), "DX target",
        HamClockModuleCategory.RF, "selected-path", true, 2, 2, preferredHeightDp = 210,
        sourceLabel = "Manual or ranked DX", renderer = HamClockModuleRenderer.DX_TARGET,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Target, bearing and distance rows"),
    HamClockModuleSpec(HamClockPanelId.VOACAP, setOf("propagation", "propagation-chart", "propagation-bars"),
        "Propagation", HamClockModuleCategory.RF, "path-prediction", true, 2, 3, preferredHeightDp = 240,
        sourceLabel = "OpenHamClock public estimate", renderer = HamClockModuleRenderer.PROPAGATION,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Bounded per-band reliability rows"),
    HamClockModuleSpec(HamClockPanelId.PORTABLE, setOf("pota", "sota", "wwff"), "Portable activators",
        HamClockModuleCategory.ACTIVITY, "portable-summary", false, 2, 4, preferredHeightDp = 240,
        availability = HamClockModuleAvailability.DELEGATED, sourceLabel = "POTA · SOTA · WWFF",
        renderer = HamClockModuleRenderer.PORTABLE, deepLink = HamClockDeepLink.PORTABLE,
        lowDataRepresentation = "Bounded activator rows"),
    HamClockModuleSpec(HamClockPanelId.CONTESTS, setOf("contests"), "Contests",
        HamClockModuleCategory.OPERATIONS, "calendar", true, 2, 5,
        sourceLabel = "WA7BNM", renderer = HamClockModuleRenderer.CONTESTS,
        deepLink = HamClockDeepLink.OPERATIONS, lowDataRepresentation = "Active and upcoming contest rows"),
    HamClockModuleSpec(HamClockPanelId.BAND_ACTIVITY, setOf("band-activity", "band-conditions"), "Band activity",
        HamClockModuleCategory.RF, "band-evidence", false, 2, 6, preferredHeightDp = 260,
        sourceLabel = "ShackCQ measured evidence", renderer = HamClockModuleRenderer.BAND_ACTIVITY,
        deepLink = HamClockDeepLink.LOG_INTELLIGENCE, lowDataRepresentation = "Per-band activity counts"),
    HamClockModuleSpec(HamClockPanelId.SATELLITES, setOf("satellites"), "Satellite operations",
        HamClockModuleCategory.OPERATIONS, "next-pass", false, 2, 7,
        availability = HamClockModuleAvailability.DELEGATED, sourceLabel = "CelesTrak · SatNOGS · local SGP4",
        renderer = HamClockModuleRenderer.SATELLITES, deepLink = HamClockDeepLink.OPERATIONS,
        lowDataRepresentation = "Next-pass rows"),
    HamClockModuleSpec(HamClockPanelId.RBN, setOf("rbn"), "Reverse Beacon Network",
        HamClockModuleCategory.RF, "skimmer-observations", false, 2, 8, preferredHeightDp = 240,
        sourceLabel = "Configured retail DX cluster · RBN observations", renderer = HamClockModuleRenderer.RBN,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Bounded skimmer and DX rows"),
    HamClockModuleSpec(HamClockPanelId.WSPR, setOf("wspr"), "Personal WSPR",
        HamClockModuleCategory.RF, "personal-wspr-paths", false, 2, 9, preferredHeightDp = 230,
        sourceLabel = "PSK Reporter · mode WSPR", renderer = HamClockModuleRenderer.WSPR,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Bounded sender and receiver rows"),
    HamClockModuleSpec(HamClockPanelId.IBP, setOf("ibp"), "IBP schedule",
        HamClockModuleCategory.RF, "beacon-schedule-reference", false, 2, 10, preferredHeightDp = 220,
        sourceLabel = "NCDXF/IARU schedule manifest", renderer = HamClockModuleRenderer.IBP,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Current five-band schedule; not heard evidence"),
    HamClockModuleSpec(HamClockPanelId.BAND_HEALTH, setOf("band-health"), "Band Health",
        HamClockModuleCategory.RF, "measured-band-evidence", false, 2, 11, preferredHeightDp = 280,
        sourceLabel = "Cluster · PSK · RBN · personal WSPR", renderer = HamClockModuleRenderer.BAND_HEALTH,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Explainable per-band evidence rows"),
    HamClockModuleSpec(HamClockPanelId.NEURAL_OUTLOOK, setOf("neural-outlook"), "Neural outlook",
        HamClockModuleCategory.RF, "empirical-future-window", true, 2, 12, preferredHeightDp = 250,
        sourceLabel = "ShackCQ Empirical Outlook v1", renderer = HamClockModuleRenderer.NEURAL_OUTLOOK,
        deepLink = HamClockDeepLink.DX, lowDataRepresentation = "Window, supported bands, confidence and calibration"),
    HamClockModuleSpec(HamClockPanelId.ANALOG_CLOCK, setOf("analog-clock"), "Analog clock",
        HamClockModuleCategory.STATION, "native-clock-face", false, 0, 4, preferredHeightDp = 220,
        sourceLabel = "Local time calculation", renderer = HamClockModuleRenderer.ANALOG_CLOCK,
        lowDataRepresentation = "Digital time equivalent"),
)

internal fun hamClockModuleSpec(id: String): HamClockModuleSpec? =
    hamClockModuleRegistry.firstOrNull { it.id == id }

internal fun defaultPanelsFromRegistry(): List<HamClockPanelPreference> =
    hamClockModuleRegistry.map { spec ->
        HamClockPanelPreference(
            id = spec.id,
            visible = spec.defaultVisible,
            order = spec.defaultOrder,
            column = spec.defaultColumn,
            columnSpan = spec.defaultColumnSpan,
            rowSpan = spec.defaultRowSpan,
        )
    }

internal enum class HamClockMapLayerCategory { STATION, DX, REPORTS, PORTABLE, SPACE, LOG, WEATHER, REFERENCE, FUTURE }
internal enum class HamClockMapLayerAvailability { ACTIVE, DELEGATED, UNAVAILABLE }
internal enum class HamClockMapRenderKind { POINT, LINE, FILL }
internal enum class HamClockMapSelection {
    NONE, DX_SPOT, PSK_REPORT, RBN_OBSERVATION, WSPR_OBSERVATION, IBP_BEACON,
    PORTABLE, SATELLITE, QSO, TARGET, WEATHER
}

internal data class HamClockMapLayerSpec(
    val id: String,
    val upstreamId: String,
    val title: String,
    val category: HamClockMapLayerCategory,
    val defaultVisible: Boolean,
    val defaultOpacity: Float = 1f,
    val availability: HamClockMapLayerAvailability,
    val unavailableReason: String = "",
    val sourceLabel: String,
    val renderKinds: Set<HamClockMapRenderKind>,
    val selection: HamClockMapSelection = HamClockMapSelection.NONE,
    val lowDataRepresentation: String,
    val maximumObjectCount: Int,
) {
    val sourcePrefix: String get() = "hamclock-$id"
}

internal val hamClockMapLayerRegistry = listOf(
    HamClockMapLayerSpec(HamClockMapLayerId.DE_STATION, "de-location", "DE station", HamClockMapLayerCategory.STATION,
        true, availability = HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Configured station",
        renderKinds = setOf(HamClockMapRenderKind.POINT), lowDataRepresentation = "Station callsign and grid", maximumObjectCount = 1),
    HamClockMapLayerSpec(HamClockMapLayerId.DX_SPOTS, "dx-cluster", "DX spots", HamClockMapLayerCategory.DX,
        true, availability = HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Configured DX cluster",
        renderKinds = setOf(HamClockMapRenderKind.POINT), selection = HamClockMapSelection.DX_SPOT,
        lowDataRepresentation = "Bounded filtered spot rows", maximumObjectCount = 160),
    HamClockMapLayerSpec(HamClockMapLayerId.DX_PATHS, "great-circle", "DX reporting paths", HamClockMapLayerCategory.DX,
        true, .62f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Local geodesic geometry",
        renderKinds = setOf(HamClockMapRenderKind.LINE), selection = HamClockMapSelection.DX_SPOT,
        lowDataRepresentation = "Reporter to DX path rows", maximumObjectCount = 80),
    HamClockMapLayerSpec(HamClockMapLayerId.SELECTED_TARGET, "great-circle", "Selected DX target", HamClockMapLayerCategory.DX,
        true, availability = HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Manual or ranked DX target",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE), selection = HamClockMapSelection.TARGET,
        lowDataRepresentation = "Target source, distance and bearing", maximumObjectCount = 2),
    HamClockMapLayerSpec(HamClockMapLayerId.PSK_REPORTER, "psk-reporter", "PSK Reporter", HamClockMapLayerCategory.REPORTS,
        false, .72f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "PSK Reporter",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE), selection = HamClockMapSelection.PSK_REPORT,
        lowDataRepresentation = "Bounded report rows", maximumObjectCount = 60),
    HamClockMapLayerSpec(HamClockMapLayerId.PORTABLE, "pota", "Portable activity", HamClockMapLayerCategory.PORTABLE,
        true, availability = HamClockMapLayerAvailability.DELEGATED, sourceLabel = "POTA · SOTA · WWFF",
        renderKinds = setOf(HamClockMapRenderKind.POINT), selection = HamClockMapSelection.PORTABLE,
        lowDataRepresentation = "Bounded activator rows", maximumObjectCount = 160),
    HamClockMapLayerSpec(HamClockMapLayerId.SATELLITES, "satellites", "Satellite positions", HamClockMapLayerCategory.SPACE,
        false, availability = HamClockMapLayerAvailability.DELEGATED, sourceLabel = "CelesTrak · SatNOGS · local SGP4",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE, HamClockMapRenderKind.FILL), selection = HamClockMapSelection.SATELLITE,
        lowDataRepresentation = "Current positions, up to four tracks and footprints", maximumObjectCount = 40),
    HamClockMapLayerSpec(HamClockMapLayerId.LOGGED_QSOS, "n3fjp_logged_qsos", "Recent logged QSOs", HamClockMapLayerCategory.LOG,
        false, .75f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "ShackCQ compact projection",
        renderKinds = setOf(HamClockMapRenderKind.POINT), selection = HamClockMapSelection.QSO,
        lowDataRepresentation = "Most recent bounded QSO rows", maximumObjectCount = 120),
    HamClockMapLayerSpec(HamClockMapLayerId.CONTEST_QSOS, "contest_qsos", "Contest QSOs", HamClockMapLayerCategory.LOG,
        false, .78f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "ShackCQ indexed QSO projection",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE), selection = HamClockMapSelection.QSO,
        lowDataRepresentation = "Bounded selected-contest QSO rows", maximumObjectCount = 200),
    HamClockMapLayerSpec(HamClockMapLayerId.GRAYLINE, "grayline", "Grayline and night", HamClockMapLayerCategory.SPACE,
        true, .58f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Local astronomy",
        renderKinds = setOf(HamClockMapRenderKind.FILL, HamClockMapRenderKind.LINE),
        lowDataRepresentation = "Current UTC terminator state", maximumObjectCount = 2),
    HamClockMapLayerSpec(HamClockMapLayerId.SUN, "grayline", "Sun", HamClockMapLayerCategory.SPACE,
        true, availability = HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Local astronomy",
        renderKinds = setOf(HamClockMapRenderKind.POINT), lowDataRepresentation = "Subsolar point", maximumObjectCount = 1),
    HamClockMapLayerSpec(HamClockMapLayerId.MOON, "lunar", "Moon", HamClockMapLayerCategory.SPACE,
        false, availability = HamClockMapLayerAvailability.UNAVAILABLE,
        unavailableReason = "Truthful sublunar geometry is not implemented; the Moon phase panel remains available",
        sourceLabel = "Local Moon phase only", renderKinds = emptySet(),
        lowDataRepresentation = "Moon phase is available in Solar conditions; no map marker", maximumObjectCount = 0),
    HamClockMapLayerSpec(HamClockMapLayerId.GRID, "maidenhead-grid", "Maidenhead fields", HamClockMapLayerCategory.REFERENCE,
        false, .45f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Local Maidenhead geometry",
        renderKinds = setOf(HamClockMapRenderKind.LINE), lowDataRepresentation = "32 field-boundary lines", maximumObjectCount = 32),
    HamClockMapLayerSpec(HamClockMapLayerId.LIGHTNING, "lightning", "Lightning", HamClockMapLayerCategory.WEATHER,
        false, availability = HamClockMapLayerAvailability.ACTIVE, sourceLabel = "ShackCQ DX weather authority",
        renderKinds = setOf(HamClockMapRenderKind.POINT), selection = HamClockMapSelection.WEATHER,
        lowDataRepresentation = "Bounded recent strikes", maximumObjectCount = 120),
    HamClockMapLayerSpec(HamClockMapLayerId.RBN, "rbn", "Reverse Beacon Network", HamClockMapLayerCategory.REPORTS,
        false, .72f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "Configured retail DX cluster",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE),
        selection = HamClockMapSelection.RBN_OBSERVATION, lowDataRepresentation = "Bounded RBN observations", maximumObjectCount = 120),
    HamClockMapLayerSpec(HamClockMapLayerId.WSPR_EXPANDED, "wspr", "Personal WSPR paths", HamClockMapLayerCategory.REPORTS,
        false, .68f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "PSK Reporter · mode WSPR",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE),
        selection = HamClockMapSelection.WSPR_OBSERVATION, lowDataRepresentation = "Bounded personal WSPR observations", maximumObjectCount = 100),
    HamClockMapLayerSpec(HamClockMapLayerId.IBP, "ibp", "IBP beacons", HamClockMapLayerCategory.REFERENCE,
        false, .8f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "NCDXF/IARU schedule manifest",
        renderKinds = setOf(HamClockMapRenderKind.POINT, HamClockMapRenderKind.LINE),
        selection = HamClockMapSelection.IBP_BEACON, lowDataRepresentation = "18 sites and five scheduled paths", maximumObjectCount = 23),
    HamClockMapLayerSpec(HamClockMapLayerId.AURORA, "aurora", "Aurora", HamClockMapLayerCategory.SPACE,
        false, .6f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "NOAA SWPC OVATION Aurora Forecast",
        renderKinds = setOf(HamClockMapRenderKind.FILL), lowDataRepresentation = "Bounded regional probability summary", maximumObjectCount = 180),
    HamClockMapLayerSpec(HamClockMapLayerId.NEURAL_OUTLOOK, "neural-outlook", "Empirical outlook", HamClockMapLayerCategory.FUTURE,
        false, .58f, HamClockMapLayerAvailability.ACTIVE, sourceLabel = "ShackCQ Empirical Outlook v1",
        renderKinds = setOf(HamClockMapRenderKind.FILL), lowDataRepresentation = "72 bounded world-region cells",
        maximumObjectCount = 72),
    HamClockMapLayerSpec(HamClockMapLayerId.MUF, "muf-map", "MUF map", HamClockMapLayerCategory.FUTURE,
        false, availability = HamClockMapLayerAvailability.UNAVAILABLE, unavailableReason = "No global MUF source",
        sourceLabel = "Not connected", renderKinds = emptySet(), lowDataRepresentation = "Unavailable", maximumObjectCount = 0),
    HamClockMapLayerSpec(HamClockMapLayerId.PROPAGATION_HEATMAP, "voacap-heatmap", "Propagation heatmap", HamClockMapLayerCategory.FUTURE,
        false, availability = HamClockMapLayerAvailability.UNAVAILABLE, unavailableReason = "No bounded global heatmap contract",
        sourceLabel = "Not connected", renderKinds = emptySet(), lowDataRepresentation = "Unavailable", maximumObjectCount = 0),
    HamClockMapLayerSpec(HamClockMapLayerId.WEATHER_RADAR, "wxradar", "Weather radar", HamClockMapLayerCategory.FUTURE,
        false, availability = HamClockMapLayerAvailability.UNAVAILABLE, unavailableReason = "No lawful configured radar tiles",
        sourceLabel = "Not connected", renderKinds = emptySet(), lowDataRepresentation = "Unavailable", maximumObjectCount = 0),
    HamClockMapLayerSpec(HamClockMapLayerId.WWBOTA, "wwbota", "WWBOTA", HamClockMapLayerCategory.FUTURE,
            false, availability = HamClockMapLayerAvailability.UNAVAILABLE, unavailableReason = "Provider integration is not available in this build",
        sourceLabel = "Not connected", renderKinds = emptySet(), lowDataRepresentation = "Unavailable", maximumObjectCount = 0),
)

internal fun hamClockMapLayerSpec(id: String): HamClockMapLayerSpec? =
    hamClockMapLayerRegistry.firstOrNull { it.id == id }

internal fun defaultLayersFromRegistry(): List<HamClockMapLayerPreference> =
    hamClockMapLayerRegistry.map { HamClockMapLayerPreference(it.id, it.defaultVisible, it.defaultOpacity) }
