package app.shackcq.mobile.contest

import android.database.sqlite.SQLiteDatabase
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.shackcq.mobile.QsoDatabase
import app.shackcq.mobile.QsoMutationCoordinator
import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ContestIntegrationInstrumentedTest {
    private val context get()=ApplicationProvider.getApplicationContext<android.content.Context>()
    private fun session(id:String="cq-ww-cw")=ContestSession(ContestSessionId("s"),ContestDefinitionId(id),ContestRuleVersion("1.0.0"),"Test",0,999999,"OM0RX","JN88",ContestEntityInfo(dxcc="503",continent="OC",cqZone="30",isOceania=true,isWve=false),ContestCategory(mode=ContestMode.CW),listOf("OM0RX"))
    @Test fun contestDatabaseHasNoCanonicalQsoBodyAndSerialIsTransactional(){val name="contest-test-${System.nanoTime()}.sqlite";val store=ContestSessionStore(context,name);try{val s=session("cq-wpx-cw");store.saveSession(s);val authority=ContestSerialAuthority(store){100};val r=authority.reserve(s,"radio1");assertEquals(ContestSerialState.RESERVED,r.state);authority.commit(r.id,s.id,"canonical-id");assertTrue(store.qsoLinkQueryPlan(s.id).contains("contest_qso_link_session_idx"));val db=SQLiteDatabase.openDatabase(context.getDatabasePath(name).path,null,SQLiteDatabase.OPEN_READONLY);db.use{val tables=mutableListOf<String>();it.rawQuery("SELECT name FROM sqlite_master WHERE type='table'",null).use{c->while(c.moveToNext())tables+=c.getString(0)};assertFalse(tables.contains("qso"));it.rawQuery("PRAGMA table_info(contest_qso_revision_link)",null).use{c->val columns=mutableListOf<String>();while(c.moveToNext())columns+=c.getString(1);assertEquals(setOf("session_id","qso_id","revision","linked_at"),columns.toSet())}}}finally{store.close();context.deleteDatabase(name)}}
    @Test fun temporaryContestEntryStagesWithoutCanonicalWriteAndIsIndexed(){val contestName="contest-stage-${System.nanoTime()}.sqlite";val qsoName="contest-canonical-${System.nanoTime()}.sqlite";val store=ContestSessionStore(context,contestName);val canonical=QsoDatabase(context,qsoName);try{val s=session("cq-wpx-cw");store.saveSession(s);val draft=ContestQsoDraft("stage-1","K1ABC",1000,14_050_000,ContestBand.B20,ContestMode.CW,"599","599",received=mapOf(ContestExchangeField.SERIAL to "12"));assertTrue(store.stageQso(s,draft));assertNull(canonical.qso("stage-1"));assertEquals(draft,store.stagedQsos(s.id).single().draft);assertTrue(store.contestQsoQueryPlan(s.id).contains("contest_qso_merge_idx"));assertFalse(store.stageQso(s,draft))}finally{store.close();canonical.close();context.deleteDatabase(contestName);context.deleteDatabase(qsoName)}}
    @Test fun contestSaveUsesCanonicalCoordinatorAndAdifRoundTrips(){val name="qso-contest-${System.nanoTime()}.sqlite";val db=QsoDatabase(context,name);try{val registry=ContestRuleRegistry();val definition=registry.require(ContestDefinitionId("cq-wpx-cw")).definition;val s=session("cq-wpx-cw");val repo=ContestRepository(CoordinatorContestQsoMutationPort(QsoMutationCoordinator(db)),null,ContestSerialAuthority(InMemoryContestSerialStore()));val draft=ContestQsoDraft("q1","K1ABC",1000,14_050_000,ContestBand.B20,ContestMode.CW,"599","599",received=mapOf(ContestExchangeField.SERIAL to "12"),worked=ContestEntityInfo(dxcc="291",continent="NA",wpxPrefix="K1"),station=s.station);val result=repo.save(s,definition,draft,"radio1");assertTrue(result.accepted);val canonical=requireNotNull(db.qso("q1"));val adif=db.toADIF(canonical);assertTrue(adif.contains("<CONTEST_ID:9>CQ-WPX-CW"));assertTrue(adif.contains("<SRX:2>12"));assertTrue(adif.contains("APP_SHACKCQ_CONTEST_SESSION"))}finally{db.close();context.deleteDatabase(name)}}
    @Test fun processRecreationRestoresScoreButNeverNetworkOrKeyerArming(){val name="contest-restore-${System.nanoTime()}.sqlite";val first=ContestSessionStore(context,name);val expected=session().copy(state=ContestSessionState.RUNNING,networkArmed=true,keyerArmed=true,score=ContestScoreSnapshot(points=42,claimedScore=420));first.saveSession(expected);first.close();val reopened=ContestSessionStore(context,name);try{val restored=ContestSessionController().restored(requireNotNull(reopened.loadSession(expected.id)));assertEquals(42,restored.score.points);assertEquals(ContestSessionState.PAUSED,restored.state);assertFalse(restored.networkArmed);assertFalse(restored.keyerArmed)}finally{reopened.close();context.deleteDatabase(name)}}
}
