#include "shackcq/desktop/WavelogRadioBridge.hpp"
#include "shackcq/desktop/DesktopRadioController.hpp"

#include <QDateTime>
#include <QHostAddress>
#include <QJsonDocument>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QRegularExpression>
#include <QTcpSocket>
#include <QUuid>

namespace shackcq::desktop {
namespace {
QUrl baseUrl(const QString &value){QUrl url(value.trimmed());if(url.scheme()!="https"||url.host().isEmpty())return{};url.setQuery({});url.setFragment({});QString path=url.path();while(path.endsWith('/'))path.chop(1);if(!path.endsWith("/index.php"))path+="/index.php";url.setPath(path+QChar('/'));return url;}
const QSet<QString>& modes(){static const QSet<QString> value{"lsb","usb","cw","fm","am","rtty","pkt","dig","pktlsb","pktusb","pktfm"};return value;}
}

WavelogRadioBridge::WavelogRadioBridge(DesktopRadioController *radio,QObject *parent):QObject(parent),m_radio(radio){m_publishTimer.setInterval(5000);connect(&m_publishTimer,&QTimer::timeout,this,&WavelogRadioBridge::publish);connect(&m_server,&QTcpServer::newConnection,this,&WavelogRadioBridge::acceptConnections);if(m_radio)connect(m_radio,&DesktopRadioController::snapshotChanged,this,[this]{if(m_publishTimer.isActive())publish();});}
QString WavelogRadioBridge::callbackUrl()const{return m_server.isListening()?QStringLiteral("http://127.0.0.1:%1/%2").arg(m_server.serverPort()).arg(m_nonce):QString{};}
QVariantMap WavelogRadioBridge::capabilities()const{return{{"radioStatePublish",true},{"legacyClickToTune",(m_apiMode=="LEGACY"||m_apiMode=="AUTO")&&m_radio&&m_radio->tuneAvailable()},{"v2ClickToTune",false},{"rotator",false},{"digitalAudio",false},{"ptt",false},{"owner","DesktopRadioController"},{"callbackBoundary","available only when the existing controller grants receive tuning"}};}
QJsonObject WavelogRadioBridge::radioState(const QString &name,quint64 frequencyHz,const QString &mode,const QUrl &callback){QJsonObject body{{"radio",name.left(80)},{"frequency",static_cast<qint64>(frequencyHz)},{"mode",mode.toLower().left(10)},{"timestamp",QDateTime::currentDateTimeUtc().toString("yyyy/MM/dd HH:mm:ss")}};if(callback.isValid())body.insert("cat_url",callback.toString());return body;}
bool WavelogRadioBridge::parseTunePath(const QString &path,const QString &nonce,quint64 *frequencyHz,QString *mode){const QRegularExpression expression(QStringLiteral("^/%1/(\\d{5,10})/([A-Za-z]{2,10})/?$").arg(QRegularExpression::escape(nonce)));const auto match=expression.match(path);if(!match.hasMatch())return false;bool ok=false;const quint64 frequency=match.captured(1).toULongLong(&ok);const QString normalized=match.captured(2).toLower();if(!ok||frequency<100000||frequency>6000000000ULL||!modes().contains(normalized))return false;if(frequencyHz)*frequencyHz=frequency;if(mode)*mode=normalized.toUpper();return true;}
bool WavelogRadioBridge::acceptsLoopbackHost(const QByteArray &request){const QRegularExpression expression(QStringLiteral("(?:^|\\r\\n)Host:[ \\t]*(?:127\\.0\\.0\\.1|\\[::1\\])(?::\\d{1,5})?[ \\t]*\\r\\n"),QRegularExpression::CaseInsensitiveOption);return expression.match(QString::fromLatin1(request)).hasMatch();}
bool WavelogRadioBridge::configure(const QString &serverUrl,const QString &credentialAlias,const QString &radioName,const QString &apiMode){stop();m_serverUrl=baseUrl(serverUrl);m_credentialAlias=credentialAlias.trimmed();m_radioName=radioName.trimmed();m_apiMode=apiMode.trimmed().toUpper();if(m_apiMode=="V1")m_apiMode="LEGACY";if(!m_serverUrl.isValid()||m_credentialAlias.isEmpty()||m_radioName.isEmpty()||!QStringList{"AUTO","LEGACY","V2"}.contains(m_apiMode)){setState("Invalid profile");return false;}m_nonce=QUuid::createUuid().toString(QUuid::WithoutBraces);const bool callbackPermitted=(m_apiMode=="LEGACY"||m_apiMode=="AUTO")&&m_radio&&m_radio->tuneAvailable();if(callbackPermitted&&!m_server.listen(QHostAddress::LocalHost,0)){setState("Callback unavailable");return false;}m_publishTimer.start();setState("Configured");publish();return true;}
void WavelogRadioBridge::stop(){m_publishTimer.stop();m_server.close();m_serverUrl=QUrl{};m_credentialAlias.clear();m_radioName.clear();m_nonce.clear();setState("Disabled");}
void WavelogRadioBridge::setState(const QString &state){if(m_state==state)return;m_state=state;emit stateChanged();}
void WavelogRadioBridge::publish(){if(!m_radio||!m_credentialResolver||!m_serverUrl.isValid())return;const QString credential=m_credentialResolver(m_credentialAlias);if(credential.isEmpty()){setState("Credential unavailable");return;}const bool v2=m_apiMode=="V2"||(m_apiMode=="AUTO"&&credential.startsWith("wl2_"));QUrl endpoint=m_serverUrl.resolved(QUrl(v2?"api/v2/radio":"api/radio"));QJsonObject body=radioState(m_radioName,m_radio->frequencyHz(),m_radio->mode(),v2?QUrl{}:QUrl(callbackUrl()));if(!v2)body.insert("key",credential);QNetworkRequest request(endpoint);request.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");request.setRawHeader("Accept","application/json");request.setTransferTimeout(8000);if(v2)request.setRawHeader("Authorization",QByteArray("Bearer ")+credential.toUtf8());auto *reply=m_network.post(request,QJsonDocument(body).toJson(QJsonDocument::Compact));connect(reply,&QNetworkReply::finished,this,[this,reply]{const int status=reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();if(reply->error()==QNetworkReply::NoError&&status>=200&&status<300)setState("Publishing radio state");else{setState("Publish failed");emit error(QStringLiteral("Wavelog radio publish failed (%1)").arg(status));}reply->deleteLater();});}
void WavelogRadioBridge::acceptConnections(){while(auto *socket=m_server.nextPendingConnection()){connect(socket,&QTcpSocket::readyRead,this,[this,socket]{if(socket->bytesAvailable()>4096){socket->disconnectFromHost();return;}const QByteArray bytes=socket->readAll();const int end=bytes.indexOf("\r\n");const QList<QByteArray> first=end>=0?bytes.left(end).split(' '):QList<QByteArray>{};quint64 frequency=0;QString mode;const qint64 now=QDateTime::currentMSecsSinceEpoch();const bool valid=first.size()==3&&first[0]=="GET"&&acceptsLoopbackHost(bytes)&&now-m_lastTuneMs>=250&&parseTunePath(QString::fromUtf8(first[1]),m_nonce,&frequency,&mode);bool tuned=false;if(valid&&m_radio){m_lastTuneMs=now;tuned=m_radio->requestMode(mode)&&m_radio->requestFrequency(frequency);}socket->write(tuned?"HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n":"HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");socket->disconnectFromHost();});connect(socket,&QTcpSocket::disconnected,socket,&QObject::deleteLater);}}

} // namespace shackcq::desktop
