#include "shackcq/desktop/AdifService.hpp"
#include "shackcq/desktop/QsoDatabase.hpp"
#include "shackcq/desktop/WavelogSync.hpp"

#include <QElapsedTimer>
#include <QFile>
#include <QJsonDocument>
#include <QSqlError>
#include <QSqlQuery>
#include <QTemporaryDir>
#include <QtTest>
#include <cmath>

using namespace shackcq::desktop;

class DesktopDataContractTests final : public QObject {
    Q_OBJECT
private slots:
    void schemaMigrationAndProjectionTruth() {
        QTemporaryDir dir; QsoDatabase database(dir.filePath("qso.sqlite")); QString error;
        QVERIFY2(database.open(&error), qPrintable(error));
        QSqlQuery version(database.connection()); QVERIFY(version.exec("PRAGMA user_version")); QVERIFY(version.next()); QCOMPARE(version.value(0).toInt(), 17);
        QsoRecord q; q.callsign="om0rx"; q.frequencyHz=14074000; q.mode="FT8"; q.grid="JN88TQ"; q.extraAdif.insert("APP_EXAMPLE","preserved");
        QVERIFY2(database.save(q,&error),qPrintable(error)); QCOMPARE(database.count(),1); QVERIFY2(database.verifyProjection(&error),qPrintable(error));
        const auto worked=database.workedConfirmed("OM0RX","20m","FT8"); QVERIFY(worked.value("worked").toBool()); QVERIFY(!worked.value("confirmed").toBool());
    }
    void populatedSchema16MigratesAdditivelyTo17() {
        QTemporaryDir dir;const QString path=dir.filePath("legacy.sqlite");const QString seedName="schema16-seed";
        {auto seed=QSqlDatabase::addDatabase("QSQLITE",seedName);seed.setDatabaseName(path);QVERIFY(seed.open());QSqlQuery q(seed);
            QVERIFY(q.exec("CREATE TABLE qso(id TEXT PRIMARY KEY,callsign TEXT NOT NULL,frequency_hz INTEGER NOT NULL,frequency_rx_hz INTEGER NOT NULL DEFAULT 0,band TEXT NOT NULL,band_rx TEXT NOT NULL DEFAULT '',mode TEXT NOT NULL,submode TEXT NOT NULL DEFAULT '',rst_sent TEXT NOT NULL DEFAULT '59',rst_received TEXT NOT NULL DEFAULT '59',grid TEXT NOT NULL DEFAULT '',comment TEXT NOT NULL DEFAULT '',station_profile_id TEXT NOT NULL DEFAULT '',station_callsign TEXT NOT NULL DEFAULT '',operator_callsign TEXT NOT NULL DEFAULT '',dxcc TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',cq_zone TEXT NOT NULL DEFAULT '',itu_zone TEXT NOT NULL DEFAULT '',contest_id TEXT NOT NULL DEFAULT '',satellite_name TEXT NOT NULL DEFAULT '',satellite_mode TEXT NOT NULL DEFAULT '',pota_ref TEXT NOT NULL DEFAULT '',sota_ref TEXT NOT NULL DEFAULT '',iota TEXT NOT NULL DEFAULT '',wwff_ref TEXT NOT NULL DEFAULT '',qsl_received TEXT NOT NULL DEFAULT 'N',lotw_received TEXT NOT NULL DEFAULT 'N',eqsl_received TEXT NOT NULL DEFAULT 'N',qrz_received TEXT NOT NULL DEFAULT 'N',provenance TEXT NOT NULL DEFAULT 'local',remote_id TEXT NOT NULL DEFAULT '',extra_adif_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted INTEGER NOT NULL DEFAULT 0)"));
            QVERIFY(q.exec("INSERT INTO qso(id,callsign,frequency_hz,band,mode,satellite_name,extra_adif_json,created_at,updated_at) VALUES('legacy','VK9XX',145800000,'2m','FM','AO-91','{\"APP_FUTURE\":\"keep\"}',1777000000,1777000000)"));QVERIFY(q.exec("PRAGMA user_version=16"));seed.close();}
        QSqlDatabase::removeDatabase(seedName);QsoDatabase database(path);QString error;QVERIFY2(database.open(&error),qPrintable(error));QSqlQuery version(database.connection());QVERIFY(version.exec("PRAGMA user_version"));QVERIFY(version.next());QCOMPARE(version.value(0).toInt(),17);
        const auto rows=database.page({});QCOMPARE(rows.size(),1);QCOMPARE(rows.first().id,QString("legacy"));QCOMPARE(rows.first().extraAdif.value("APP_FUTURE").toString(),QString("keep"));QCOMPARE(rows.first().propagationMode,QString("SAT"));QVERIFY(std::isnan(rows.first().txPower));QCOMPARE(rows.first().qslSent,QString(""));
    }
    void advancedQsoPersistsAndReadsEveryCanonicalField() {
        QTemporaryDir dir;QsoDatabase database(dir.filePath("advanced.sqlite"));QString error;QVERIFY(database.open(&error));QsoRecord q;q.callsign="OM0RX";q.frequencyHz=145800000;q.band="2m";q.mode="FM";q.createdAt=1777000000;q.propagationMode="SAT";q.antennaPath="G";q.txPower=5.5;q.antenna="Portable whip";q.potaRef="vk-0001, VK-0002,VK-0001";q.sotaRef="W1/AA-001,W2/BB-002";q.wwffRef="VKFF-0001,VKFF-0002";q.iota="OC-001,OC-002";q.qslManager="OM0RX";q.qslMessage="Thanks";q.qslSent="Y";q.qslReceived="Y";q.qslSentDate="2026-09-11";q.qslReceivedDate="2026-09-12";q.qslSentMethod="E";q.qslReceivedMethod="D";q.extraAdif.insert("APP_FUTURE","keep");QVERIFY2(database.save(q,&error),qPrintable(error));auto saved=database.page({}).first();QCOMPARE(saved.propagationMode,q.propagationMode);QCOMPARE(saved.antennaPath,q.antennaPath);QCOMPARE(saved.txPower,q.txPower);QCOMPARE(saved.antenna,q.antenna);QCOMPARE(saved.potaRef,QString("VK-0001,VK-0002"));QCOMPARE(saved.sotaRef,QString("W1/AA-001,W2/BB-002"));QCOMPARE(saved.wwffRef,QString("VKFF-0001,VKFF-0002"));QCOMPARE(saved.iota,QString("OC-001,OC-002"));QCOMPARE(saved.qslManager,q.qslManager);QCOMPARE(saved.qslMessage,q.qslMessage);QCOMPARE(saved.qslSent,q.qslSent);QCOMPARE(saved.qslReceived,q.qslReceived);QCOMPARE(saved.qslSentDate,q.qslSentDate);QCOMPARE(saved.qslReceivedDate,q.qslReceivedDate);QCOMPARE(saved.qslSentMethod,q.qslSentMethod);QCOMPARE(saved.qslReceivedMethod,q.qslReceivedMethod);QCOMPARE(saved.extraAdif.value("APP_FUTURE").toString(),QString("keep"));saved.txPower=0;QVERIFY2(database.save(saved,&error),qPrintable(error));QCOMPARE(database.page({}).first().txPower,0.0);
    }
    void failedMigrationPreservesVersionAndRows() {
        QTemporaryDir dir;const QString path=dir.filePath("rollback.sqlite");const QString seedName="migration-failure-seed";{auto seed=QSqlDatabase::addDatabase("QSQLITE",seedName);seed.setDatabaseName(path);QVERIFY(seed.open());QSqlQuery q(seed);QVERIFY(q.exec("CREATE TABLE qso(id TEXT PRIMARY KEY,callsign TEXT NOT NULL,frequency_hz INTEGER NOT NULL,frequency_rx_hz INTEGER NOT NULL DEFAULT 0,band TEXT NOT NULL,band_rx TEXT NOT NULL DEFAULT '',mode TEXT NOT NULL,submode TEXT NOT NULL DEFAULT '',rst_sent TEXT NOT NULL DEFAULT '59',rst_received TEXT NOT NULL DEFAULT '59',grid TEXT NOT NULL DEFAULT '',comment TEXT NOT NULL DEFAULT '',station_profile_id TEXT NOT NULL DEFAULT '',station_callsign TEXT NOT NULL DEFAULT '',operator_callsign TEXT NOT NULL DEFAULT '',dxcc TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',cq_zone TEXT NOT NULL DEFAULT '',itu_zone TEXT NOT NULL DEFAULT '',contest_id TEXT NOT NULL DEFAULT '',satellite_name TEXT NOT NULL DEFAULT '',satellite_mode TEXT NOT NULL DEFAULT '',pota_ref TEXT NOT NULL DEFAULT '',sota_ref TEXT NOT NULL DEFAULT '',iota TEXT NOT NULL DEFAULT '',wwff_ref TEXT NOT NULL DEFAULT '',qsl_received TEXT NOT NULL DEFAULT 'N',lotw_received TEXT NOT NULL DEFAULT 'N',eqsl_received TEXT NOT NULL DEFAULT 'N',qrz_received TEXT NOT NULL DEFAULT 'N',provenance TEXT NOT NULL DEFAULT 'local',remote_id TEXT NOT NULL DEFAULT '',extra_adif_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted INTEGER NOT NULL DEFAULT 0)"));QVERIFY(q.exec("INSERT INTO qso(id,callsign,frequency_hz,band,mode,satellite_name,created_at,updated_at) VALUES('preserved','OM0RX',14074000,'20m','CW','QO-100',1777000000,1777000000)"));QVERIFY(q.exec("PRAGMA user_version=16"));QVERIFY(q.exec("CREATE TRIGGER block_migration BEFORE UPDATE ON qso BEGIN SELECT RAISE(ABORT,'blocked migration'); END"));seed.close();}QSqlDatabase::removeDatabase(seedName);
        {QsoDatabase failed(path);QString error;QVERIFY(!failed.open(&error));QVERIFY(error.contains("blocked migration"));}
        const QString verifyName="migration-failure-verify";{auto verify=QSqlDatabase::addDatabase("QSQLITE",verifyName);verify.setDatabaseName(path);QVERIFY(verify.open());QSqlQuery q(verify);QVERIFY(q.exec("PRAGMA user_version"));QVERIFY(q.next());QCOMPARE(q.value(0).toInt(),16);QVERIFY(q.exec("SELECT callsign FROM qso WHERE id='preserved'"));QVERIFY(q.next());QCOMPARE(q.value(0).toString(),QString("OM0RX"));QSet<QString> columns;QVERIFY(q.exec("PRAGMA table_info(qso)"));while(q.next())columns.insert(q.value(1).toString());QVERIFY(!columns.contains("propagation_mode"));QVERIFY(!columns.contains("tx_power"));QVERIFY(!columns.contains("qsl_sent"));verify.close();}QSqlDatabase::removeDatabase(verifyName);
    }
    void advancedQsoValidationRejectsInvalidCombinations() {
        QTemporaryDir dir;QsoDatabase database(dir.filePath("invalid.sqlite"));QString error;QVERIFY(database.open(&error));QsoRecord q;q.callsign="OM0RX";q.frequencyHz=145800000;q.mode="FM";q.txPower=100001;QVERIFY(!database.save(q,&error));q.txPower=std::numeric_limits<double>::infinity();QVERIFY(!database.save(q,&error));q.txPower=5;q.satelliteName="QO-100";q.propagationMode="TR";QVERIFY(!database.save(q,&error));q.satelliteName.clear();q.propagationMode.clear();q.qslSent="N";q.qslSentDate="2026-09-11";QVERIFY(!database.save(q,&error));q.qslSent="R";q.qslSentDate.clear();q.sotaRef="bad";QVERIFY(!database.save(q,&error));q.sotaRef="W1/AA-001";QVERIFY2(database.save(q,&error),qPrintable(error));
    }
    void adifUnknownFieldRoundTrip() {
        QsoRecord q; q.callsign="VK9XX";q.frequencyHz=14074000;q.band="20m";q.mode="FT8";q.createdAt=1777000000;q.propagationMode="SAT";q.antennaPath="G";q.txPower=0;q.antenna="Portable whip";q.qslManager="OM0RX";q.qslMessage="Thanks";q.qslSent="Y";q.qslReceived="Y";q.qslSentDate="2026-09-11";q.qslReceivedDate="2026-09-12";q.qslSentMethod="E";q.qslReceivedMethod="D";q.extraAdif.insert("X_PRIVATE_EXTENSION","round-trip");q.extraAdif.insert("API_TOKEN","must-not-leak");q.extraAdif.insert("APP_SHACKCQ_OPERATION_ID","must-not-leak");
        QString error;const auto encoded=AdifService::serialize(q);const auto parsed=AdifService::parseRecord(encoded,&error);QVERIFY2(parsed.has_value(),qPrintable(error));QCOMPARE(parsed->callsign,QString("VK9XX"));QCOMPARE(parsed->propagationMode,q.propagationMode);QCOMPARE(parsed->antennaPath,q.antennaPath);QCOMPARE(parsed->txPower,q.txPower);QCOMPARE(parsed->antenna,q.antenna);QCOMPARE(parsed->qslManager,q.qslManager);QCOMPARE(parsed->qslMessage,q.qslMessage);QCOMPARE(parsed->qslSent,q.qslSent);QCOMPARE(parsed->qslReceived,q.qslReceived);QCOMPARE(parsed->qslSentDate,q.qslSentDate);QCOMPARE(parsed->qslReceivedDate,q.qslReceivedDate);QCOMPARE(parsed->qslSentMethod,q.qslSentMethod);QCOMPARE(parsed->qslReceivedMethod,q.qslReceivedMethod);QCOMPARE(parsed->extraAdif.value("X_PRIVATE_EXTENSION").toString(),QString("round-trip"));QVERIFY(!encoded.contains("must-not-leak"));QVERIFY(!encoded.contains("API_TOKEN"));QVERIFY(!encoded.contains("APP_SHACKCQ_OPERATION_ID"));QVERIFY(encoded.contains("<TX_PWR:1>0"));QVERIFY(encoded.contains("<QSLSDATE:8>20260911"));
    }
    void importedUnknownPropagationAndStrictPowerParsing() {
        QTemporaryDir dir;QsoDatabase database(dir.filePath("import.sqlite"));QString error;const QByteArray unknown="<CALL:5>VK9XX<FREQ:6>14.074<MODE:3>FT8<PROP_MODE:6>FUTURE<EOR>";const auto parsed=AdifService::parseRecord(unknown,&error);QVERIFY2(parsed.has_value(),qPrintable(error));QCOMPARE(parsed->propagationMode,QString("FUTURE"));QVERIFY2(database.open(&error),qPrintable(error));QVERIFY2(database.save(*parsed,&error),qPrintable(error));QCOMPARE(database.page({}).first().propagationMode,QString("FUTURE"));QsoRecord direct=*parsed;direct.id="direct";direct.provenance="local";QVERIFY(!database.save(direct,&error));const QByteArray malformed="<CALL:5>VK9XX<FREQ:6>14.074<MODE:3>FT8<TX_PWR:3>abc<EOR>";QVERIFY(!AdifService::parseRecord(malformed,&error).has_value());const QByteArray empty="<CALL:5>VK9XX<FREQ:6>14.074<MODE:3>FT8<TX_PWR:0><EOR>";const auto emptyParsed=AdifService::parseRecord(empty,&error);QVERIFY(emptyParsed.has_value());QVERIFY(std::isnan(emptyParsed->txPower));
    }
    void hundredThousandKeysetPaging() {
        QTemporaryDir dir;QsoDatabase database(dir.filePath("scale.sqlite"));QString error;QVERIFY(database.open(&error));auto db=database.connection();QVERIFY(db.transaction());QSqlQuery q(db);q.prepare("INSERT INTO qso(id,callsign,frequency_hz,band,mode,created_at,updated_at) VALUES(?,?,?,?,?,?,?)");
        for(int i=0;i<100000;i++){q.addBindValue(QString("fixture-%1").arg(i));q.addBindValue(QString("T%1").arg(i));q.addBindValue(14000000+i);q.addBindValue("20m");q.addBindValue("CW");q.addBindValue(1700000000+i);q.addBindValue(1700000000+i);QVERIFY2(q.exec(),qPrintable(q.lastError().text()));q.finish();}QVERIFY(db.commit());
        QElapsedTimer timer;timer.start();QsoQuery query;query.limit=250;const auto page=database.page(query,&error);QCOMPARE(page.size(),250);QVERIFY2(timer.elapsed()<2000,qPrintable(QString("Page took %1 ms").arg(timer.elapsed())));QCOMPARE(database.count(),100000);
    }
    void threeWayConflictAndSafeMerge() {
        CanonicalQso base{{{"CALL","OM0RX"},{"MODE","CW"}}};CanonicalQso local=base;local.fields["MODE"]="FT8";CanonicalQso remote=base;remote.fields["GRIDSQUARE"]="JN88TQ";
        const auto safe=WavelogSyncEngine::threeWayMerge(base,local,remote);QCOMPARE(safe.disposition,QString("SAFE_MERGE"));QVERIFY(safe.conflicts.isEmpty());
        remote.fields["MODE"]="SSB";const auto conflict=WavelogSyncEngine::threeWayMerge(base,local,remote);QCOMPARE(conflict.disposition,QString("CONFLICT"));QVERIFY(conflict.conflicts.contains("MODE"));
    }
    void desktopWavelogCanonicalIncludesAdvancedFields() {
        QsoRecord q;q.callsign="OM0RX";q.frequencyHz=145800000;q.band="2m";q.mode="FM";q.createdAt=1777000000;q.propagationMode="SAT";q.antennaPath="G";q.txPower=0;q.antenna="Portable whip";q.qslManager="OM0RX";q.qslMessage="Thanks";q.qslSent="Y";q.qslReceived="Y";q.qslSentDate="2026-09-11";q.qslReceivedDate="2026-09-12";q.qslSentMethod="E";q.qslReceivedMethod="D";q.extraAdif.insert("APP_FUTURE","keep");q.extraAdif.insert("PROP_MODE","TR");q.extraAdif.insert("AUTH_SECRET","must-not-leak");const auto canonical=WavelogSyncEngine::canonical(q);const QMap<QString,QString> expected{{"PROP_MODE","SAT"},{"ANT_PATH","G"},{"TX_PWR","0"},{"MY_ANTENNA","Portable whip"},{"QSL_VIA","OM0RX"},{"QSLMSG","Thanks"},{"QSL_SENT","Y"},{"QSL_RCVD","Y"},{"QSLSDATE","20260911"},{"QSLRDATE","20260912"},{"QSL_SENT_VIA","E"},{"QSL_RCVD_VIA","D"},{"APP_FUTURE","keep"}};for(auto it=expected.cbegin();it!=expected.cend();++it)QCOMPARE(canonical.fields.value(it.key()),it.value());QVERIFY(!canonical.fields.contains("AUTH_SECRET"));
    }
    void sharedSchema16GoldenFixtureRemainsMigrationBaseline() {
        QFile file(QStringLiteral(SHACKCQ_SHARED_FIXTURES_DIR "/schema16_qso_golden.json"));QVERIFY(file.open(QIODevice::ReadOnly));const auto object=QJsonDocument::fromJson(file.readAll()).object();QCOMPARE(object.value("schemaVersion").toInt(),16);QCOMPARE(QsoDatabase::SchemaVersion,17);const auto adif=object.value("canonicalAdif").toObject();QCOMPARE(adif.value("CALL").toString(),QString("VK9XX"));QCOMPARE(adif.value("APP_SHACKCQ_FUTURE").toString(),QString("preserved"));const auto expectations=object.value("expectations").toObject();QVERIFY(expectations.value("semanticInteroperabilityOnly").toBool());QVERIFY(!expectations.value("androidWindowsDatabaseBytesInterchangeable").toBool());
    }
};
QTEST_MAIN(DesktopDataContractTests)
#include "desktop_data_contract_tests.moc"
